//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCaPhe.MonAnService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonAnService.IMonAnService")]
    public interface IMonAnService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/DoWork", ReplyAction="http://tempuri.org/IMonAnService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/DoWork", ReplyAction="http://tempuri.org/IMonAnService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/getDSMon", ReplyAction="http://tempuri.org/IMonAnService/getDSMonResponse")]
        System.Data.DataTable getDSMon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/getDSMon", ReplyAction="http://tempuri.org/IMonAnService/getDSMonResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getDSMonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/KiemTraMon", ReplyAction="http://tempuri.org/IMonAnService/KiemTraMonResponse")]
        bool KiemTraMon(string maMon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/KiemTraMon", ReplyAction="http://tempuri.org/IMonAnService/KiemTraMonResponse")]
        System.Threading.Tasks.Task<bool> KiemTraMonAsync(string maMon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/ThemMon", ReplyAction="http://tempuri.org/IMonAnService/ThemMonResponse")]
        bool ThemMon(DTO_QLCP.MonAn ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/ThemMon", ReplyAction="http://tempuri.org/IMonAnService/ThemMonResponse")]
        System.Threading.Tasks.Task<bool> ThemMonAsync(DTO_QLCP.MonAn ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/SuaMon", ReplyAction="http://tempuri.org/IMonAnService/SuaMonResponse")]
        bool SuaMon(DTO_QLCP.MonAn ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/SuaMon", ReplyAction="http://tempuri.org/IMonAnService/SuaMonResponse")]
        System.Threading.Tasks.Task<bool> SuaMonAsync(DTO_QLCP.MonAn ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/XoaMon", ReplyAction="http://tempuri.org/IMonAnService/XoaMonResponse")]
        bool XoaMon(DTO_QLCP.MonAn ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/XoaMon", ReplyAction="http://tempuri.org/IMonAnService/XoaMonResponse")]
        System.Threading.Tasks.Task<bool> XoaMonAsync(DTO_QLCP.MonAn ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/LayMonTheoLoai", ReplyAction="http://tempuri.org/IMonAnService/LayMonTheoLoaiResponse")]
        System.Data.DataTable LayMonTheoLoai(string maLoaiMon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonAnService/LayMonTheoLoai", ReplyAction="http://tempuri.org/IMonAnService/LayMonTheoLoaiResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> LayMonTheoLoaiAsync(string maLoaiMon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonAnServiceChannel : QuanLiCaPhe.MonAnService.IMonAnService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonAnServiceClient : System.ServiceModel.ClientBase<QuanLiCaPhe.MonAnService.IMonAnService>, QuanLiCaPhe.MonAnService.IMonAnService {
        
        public MonAnServiceClient() {
        }
        
        public MonAnServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonAnServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonAnServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonAnServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataTable getDSMon() {
            return base.Channel.getDSMon();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getDSMonAsync() {
            return base.Channel.getDSMonAsync();
        }
        
        public bool KiemTraMon(string maMon) {
            return base.Channel.KiemTraMon(maMon);
        }
        
        public System.Threading.Tasks.Task<bool> KiemTraMonAsync(string maMon) {
            return base.Channel.KiemTraMonAsync(maMon);
        }
        
        public bool ThemMon(DTO_QLCP.MonAn ma) {
            return base.Channel.ThemMon(ma);
        }
        
        public System.Threading.Tasks.Task<bool> ThemMonAsync(DTO_QLCP.MonAn ma) {
            return base.Channel.ThemMonAsync(ma);
        }
        
        public bool SuaMon(DTO_QLCP.MonAn ma) {
            return base.Channel.SuaMon(ma);
        }
        
        public System.Threading.Tasks.Task<bool> SuaMonAsync(DTO_QLCP.MonAn ma) {
            return base.Channel.SuaMonAsync(ma);
        }
        
        public bool XoaMon(DTO_QLCP.MonAn ma) {
            return base.Channel.XoaMon(ma);
        }
        
        public System.Threading.Tasks.Task<bool> XoaMonAsync(DTO_QLCP.MonAn ma) {
            return base.Channel.XoaMonAsync(ma);
        }
        
        public System.Data.DataTable LayMonTheoLoai(string maLoaiMon) {
            return base.Channel.LayMonTheoLoai(maLoaiMon);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LayMonTheoLoaiAsync(string maLoaiMon) {
            return base.Channel.LayMonTheoLoaiAsync(maLoaiMon);
        }
    }
}
