//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCaPhe.HoaDonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HoaDonService.IHoaDonService")]
    public interface IHoaDonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoaDonService/DoWork", ReplyAction="http://tempuri.org/IHoaDonService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoaDonService/DoWork", ReplyAction="http://tempuri.org/IHoaDonService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoaDonService/getHoaDon", ReplyAction="http://tempuri.org/IHoaDonService/getHoaDonResponse")]
        System.Data.DataTable getHoaDon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoaDonService/getHoaDon", ReplyAction="http://tempuri.org/IHoaDonService/getHoaDonResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getHoaDonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoaDonService/layMaHD", ReplyAction="http://tempuri.org/IHoaDonService/layMaHDResponse")]
        string layMaHD(int maOder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoaDonService/layMaHD", ReplyAction="http://tempuri.org/IHoaDonService/layMaHDResponse")]
        System.Threading.Tasks.Task<string> layMaHDAsync(int maOder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoaDonService/ThemHD", ReplyAction="http://tempuri.org/IHoaDonService/ThemHDResponse")]
        bool ThemHD(DTO_QLCP.HoaDon hd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoaDonService/ThemHD", ReplyAction="http://tempuri.org/IHoaDonService/ThemHDResponse")]
        System.Threading.Tasks.Task<bool> ThemHDAsync(DTO_QLCP.HoaDon hd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoaDonService/XoaHD", ReplyAction="http://tempuri.org/IHoaDonService/XoaHDResponse")]
        bool XoaHD(DTO_QLCP.HoaDon hd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoaDonService/XoaHD", ReplyAction="http://tempuri.org/IHoaDonService/XoaHDResponse")]
        System.Threading.Tasks.Task<bool> XoaHDAsync(DTO_QLCP.HoaDon hd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoaDonService/ChuyenBan", ReplyAction="http://tempuri.org/IHoaDonService/ChuyenBanResponse")]
        bool ChuyenBan(DTO_QLCP.HoaDon hd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoaDonService/ChuyenBan", ReplyAction="http://tempuri.org/IHoaDonService/ChuyenBanResponse")]
        System.Threading.Tasks.Task<bool> ChuyenBanAsync(DTO_QLCP.HoaDon hd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHoaDonServiceChannel : QuanLiCaPhe.HoaDonService.IHoaDonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoaDonServiceClient : System.ServiceModel.ClientBase<QuanLiCaPhe.HoaDonService.IHoaDonService>, QuanLiCaPhe.HoaDonService.IHoaDonService {
        
        public HoaDonServiceClient() {
        }
        
        public HoaDonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HoaDonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoaDonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoaDonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataTable getHoaDon() {
            return base.Channel.getHoaDon();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getHoaDonAsync() {
            return base.Channel.getHoaDonAsync();
        }
        
        public string layMaHD(int maOder) {
            return base.Channel.layMaHD(maOder);
        }
        
        public System.Threading.Tasks.Task<string> layMaHDAsync(int maOder) {
            return base.Channel.layMaHDAsync(maOder);
        }
        
        public bool ThemHD(DTO_QLCP.HoaDon hd) {
            return base.Channel.ThemHD(hd);
        }
        
        public System.Threading.Tasks.Task<bool> ThemHDAsync(DTO_QLCP.HoaDon hd) {
            return base.Channel.ThemHDAsync(hd);
        }
        
        public bool XoaHD(DTO_QLCP.HoaDon hd) {
            return base.Channel.XoaHD(hd);
        }
        
        public System.Threading.Tasks.Task<bool> XoaHDAsync(DTO_QLCP.HoaDon hd) {
            return base.Channel.XoaHDAsync(hd);
        }
        
        public bool ChuyenBan(DTO_QLCP.HoaDon hd) {
            return base.Channel.ChuyenBan(hd);
        }
        
        public System.Threading.Tasks.Task<bool> ChuyenBanAsync(DTO_QLCP.HoaDon hd) {
            return base.Channel.ChuyenBanAsync(hd);
        }
    }
}
