//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCaPhe.NguyenLieuCPService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NguyenLieuCPService.INguyenLieuServicesCP")]
    public interface INguyenLieuServicesCP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/DoWork", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/DoWork", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/getDSNL", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/getDSNLResponse")]
        System.Data.DataTable getDSNL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/getDSNL", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/getDSNLResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getDSNLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/getDSNL_theoma", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/getDSNL_theomaResponse")]
        System.Data.DataTable getDSNL_theoma(string maNL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/getDSNL_theoma", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/getDSNL_theomaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getDSNL_theomaAsync(string maNL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/kiemTraNL", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/kiemTraNLResponse")]
        bool kiemTraNL(string maNL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/kiemTraNL", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/kiemTraNLResponse")]
        System.Threading.Tasks.Task<bool> kiemTraNLAsync(string maNL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/ThemNL", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/ThemNLResponse")]
        bool ThemNL(DTO_QLCP.NguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/ThemNL", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/ThemNLResponse")]
        System.Threading.Tasks.Task<bool> ThemNLAsync(DTO_QLCP.NguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/SuaNL", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/SuaNLResponse")]
        bool SuaNL(DTO_QLCP.NguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/SuaNL", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/SuaNLResponse")]
        System.Threading.Tasks.Task<bool> SuaNLAsync(DTO_QLCP.NguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/XoaNL", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/XoaNLResponse")]
        bool XoaNL(DTO_QLCP.NguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServicesCP/XoaNL", ReplyAction="http://tempuri.org/INguyenLieuServicesCP/XoaNLResponse")]
        System.Threading.Tasks.Task<bool> XoaNLAsync(DTO_QLCP.NguyenLieu nl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INguyenLieuServicesCPChannel : QuanLiCaPhe.NguyenLieuCPService.INguyenLieuServicesCP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NguyenLieuServicesCPClient : System.ServiceModel.ClientBase<QuanLiCaPhe.NguyenLieuCPService.INguyenLieuServicesCP>, QuanLiCaPhe.NguyenLieuCPService.INguyenLieuServicesCP {
        
        public NguyenLieuServicesCPClient() {
        }
        
        public NguyenLieuServicesCPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NguyenLieuServicesCPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NguyenLieuServicesCPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NguyenLieuServicesCPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataTable getDSNL() {
            return base.Channel.getDSNL();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getDSNLAsync() {
            return base.Channel.getDSNLAsync();
        }
        
        public System.Data.DataTable getDSNL_theoma(string maNL) {
            return base.Channel.getDSNL_theoma(maNL);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getDSNL_theomaAsync(string maNL) {
            return base.Channel.getDSNL_theomaAsync(maNL);
        }
        
        public bool kiemTraNL(string maNL) {
            return base.Channel.kiemTraNL(maNL);
        }
        
        public System.Threading.Tasks.Task<bool> kiemTraNLAsync(string maNL) {
            return base.Channel.kiemTraNLAsync(maNL);
        }
        
        public bool ThemNL(DTO_QLCP.NguyenLieu nl) {
            return base.Channel.ThemNL(nl);
        }
        
        public System.Threading.Tasks.Task<bool> ThemNLAsync(DTO_QLCP.NguyenLieu nl) {
            return base.Channel.ThemNLAsync(nl);
        }
        
        public bool SuaNL(DTO_QLCP.NguyenLieu nl) {
            return base.Channel.SuaNL(nl);
        }
        
        public System.Threading.Tasks.Task<bool> SuaNLAsync(DTO_QLCP.NguyenLieu nl) {
            return base.Channel.SuaNLAsync(nl);
        }
        
        public bool XoaNL(DTO_QLCP.NguyenLieu nl) {
            return base.Channel.XoaNL(nl);
        }
        
        public System.Threading.Tasks.Task<bool> XoaNLAsync(DTO_QLCP.NguyenLieu nl) {
            return base.Channel.XoaNLAsync(nl);
        }
    }
}
