//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCaPhe.LoaiMonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoaiMonService.ILoaiMonService")]
    public interface ILoaiMonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiMonService/DoWork", ReplyAction="http://tempuri.org/ILoaiMonService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiMonService/DoWork", ReplyAction="http://tempuri.org/ILoaiMonService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiMonService/GetLoaiMon", ReplyAction="http://tempuri.org/ILoaiMonService/GetLoaiMonResponse")]
        System.Data.DataTable GetLoaiMon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiMonService/GetLoaiMon", ReplyAction="http://tempuri.org/ILoaiMonService/GetLoaiMonResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetLoaiMonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiMonService/KiemTraLoaiMon", ReplyAction="http://tempuri.org/ILoaiMonService/KiemTraLoaiMonResponse")]
        bool KiemTraLoaiMon(string maLoaiMon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiMonService/KiemTraLoaiMon", ReplyAction="http://tempuri.org/ILoaiMonService/KiemTraLoaiMonResponse")]
        System.Threading.Tasks.Task<bool> KiemTraLoaiMonAsync(string maLoaiMon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiMonService/ThemLoaiMon", ReplyAction="http://tempuri.org/ILoaiMonService/ThemLoaiMonResponse")]
        bool ThemLoaiMon(DTO_QLCP.LoaiMon lm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiMonService/ThemLoaiMon", ReplyAction="http://tempuri.org/ILoaiMonService/ThemLoaiMonResponse")]
        System.Threading.Tasks.Task<bool> ThemLoaiMonAsync(DTO_QLCP.LoaiMon lm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiMonService/SuaLoaiMon", ReplyAction="http://tempuri.org/ILoaiMonService/SuaLoaiMonResponse")]
        bool SuaLoaiMon(DTO_QLCP.LoaiMon lm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiMonService/SuaLoaiMon", ReplyAction="http://tempuri.org/ILoaiMonService/SuaLoaiMonResponse")]
        System.Threading.Tasks.Task<bool> SuaLoaiMonAsync(DTO_QLCP.LoaiMon lm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiMonService/XoaLoaiMon", ReplyAction="http://tempuri.org/ILoaiMonService/XoaLoaiMonResponse")]
        bool XoaLoaiMon(DTO_QLCP.LoaiMon lm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiMonService/XoaLoaiMon", ReplyAction="http://tempuri.org/ILoaiMonService/XoaLoaiMonResponse")]
        System.Threading.Tasks.Task<bool> XoaLoaiMonAsync(DTO_QLCP.LoaiMon lm);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoaiMonServiceChannel : QuanLiCaPhe.LoaiMonService.ILoaiMonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoaiMonServiceClient : System.ServiceModel.ClientBase<QuanLiCaPhe.LoaiMonService.ILoaiMonService>, QuanLiCaPhe.LoaiMonService.ILoaiMonService {
        
        public LoaiMonServiceClient() {
        }
        
        public LoaiMonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoaiMonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoaiMonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoaiMonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataTable GetLoaiMon() {
            return base.Channel.GetLoaiMon();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetLoaiMonAsync() {
            return base.Channel.GetLoaiMonAsync();
        }
        
        public bool KiemTraLoaiMon(string maLoaiMon) {
            return base.Channel.KiemTraLoaiMon(maLoaiMon);
        }
        
        public System.Threading.Tasks.Task<bool> KiemTraLoaiMonAsync(string maLoaiMon) {
            return base.Channel.KiemTraLoaiMonAsync(maLoaiMon);
        }
        
        public bool ThemLoaiMon(DTO_QLCP.LoaiMon lm) {
            return base.Channel.ThemLoaiMon(lm);
        }
        
        public System.Threading.Tasks.Task<bool> ThemLoaiMonAsync(DTO_QLCP.LoaiMon lm) {
            return base.Channel.ThemLoaiMonAsync(lm);
        }
        
        public bool SuaLoaiMon(DTO_QLCP.LoaiMon lm) {
            return base.Channel.SuaLoaiMon(lm);
        }
        
        public System.Threading.Tasks.Task<bool> SuaLoaiMonAsync(DTO_QLCP.LoaiMon lm) {
            return base.Channel.SuaLoaiMonAsync(lm);
        }
        
        public bool XoaLoaiMon(DTO_QLCP.LoaiMon lm) {
            return base.Channel.XoaLoaiMon(lm);
        }
        
        public System.Threading.Tasks.Task<bool> XoaLoaiMonAsync(DTO_QLCP.LoaiMon lm) {
            return base.Channel.XoaLoaiMonAsync(lm);
        }
    }
}
