//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCaPhe.BanCoKhachService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BanCoKhachService.IBanCoKhachService")]
    public interface IBanCoKhachService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanCoKhachService/DoWork", ReplyAction="http://tempuri.org/IBanCoKhachService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanCoKhachService/DoWork", ReplyAction="http://tempuri.org/IBanCoKhachService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanCoKhachService/kiemTraBanCoKhach", ReplyAction="http://tempuri.org/IBanCoKhachService/kiemTraBanCoKhachResponse")]
        bool kiemTraBanCoKhach(string maban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanCoKhachService/kiemTraBanCoKhach", ReplyAction="http://tempuri.org/IBanCoKhachService/kiemTraBanCoKhachResponse")]
        System.Threading.Tasks.Task<bool> kiemTraBanCoKhachAsync(string maban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanCoKhachService/laySoBan", ReplyAction="http://tempuri.org/IBanCoKhachService/laySoBanResponse")]
        string laySoBan(string maBan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanCoKhachService/laySoBan", ReplyAction="http://tempuri.org/IBanCoKhachService/laySoBanResponse")]
        System.Threading.Tasks.Task<string> laySoBanAsync(string maBan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanCoKhachService/ThemBanCoKhach", ReplyAction="http://tempuri.org/IBanCoKhachService/ThemBanCoKhachResponse")]
        bool ThemBanCoKhach(DTO_QLCP.BanCoKhach ban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanCoKhachService/ThemBanCoKhach", ReplyAction="http://tempuri.org/IBanCoKhachService/ThemBanCoKhachResponse")]
        System.Threading.Tasks.Task<bool> ThemBanCoKhachAsync(DTO_QLCP.BanCoKhach ban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanCoKhachService/XoaBanCoKhach", ReplyAction="http://tempuri.org/IBanCoKhachService/XoaBanCoKhachResponse")]
        bool XoaBanCoKhach(DTO_QLCP.BanCoKhach ban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanCoKhachService/XoaBanCoKhach", ReplyAction="http://tempuri.org/IBanCoKhachService/XoaBanCoKhachResponse")]
        System.Threading.Tasks.Task<bool> XoaBanCoKhachAsync(DTO_QLCP.BanCoKhach ban);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBanCoKhachServiceChannel : QuanLiCaPhe.BanCoKhachService.IBanCoKhachService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanCoKhachServiceClient : System.ServiceModel.ClientBase<QuanLiCaPhe.BanCoKhachService.IBanCoKhachService>, QuanLiCaPhe.BanCoKhachService.IBanCoKhachService {
        
        public BanCoKhachServiceClient() {
        }
        
        public BanCoKhachServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanCoKhachServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanCoKhachServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanCoKhachServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool kiemTraBanCoKhach(string maban) {
            return base.Channel.kiemTraBanCoKhach(maban);
        }
        
        public System.Threading.Tasks.Task<bool> kiemTraBanCoKhachAsync(string maban) {
            return base.Channel.kiemTraBanCoKhachAsync(maban);
        }
        
        public string laySoBan(string maBan) {
            return base.Channel.laySoBan(maBan);
        }
        
        public System.Threading.Tasks.Task<string> laySoBanAsync(string maBan) {
            return base.Channel.laySoBanAsync(maBan);
        }
        
        public bool ThemBanCoKhach(DTO_QLCP.BanCoKhach ban) {
            return base.Channel.ThemBanCoKhach(ban);
        }
        
        public System.Threading.Tasks.Task<bool> ThemBanCoKhachAsync(DTO_QLCP.BanCoKhach ban) {
            return base.Channel.ThemBanCoKhachAsync(ban);
        }
        
        public bool XoaBanCoKhach(DTO_QLCP.BanCoKhach ban) {
            return base.Channel.XoaBanCoKhach(ban);
        }
        
        public System.Threading.Tasks.Task<bool> XoaBanCoKhachAsync(DTO_QLCP.BanCoKhach ban) {
            return base.Channel.XoaBanCoKhachAsync(ban);
        }
    }
}
