//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCaPhe.NXNguyenLieuService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NXNguyenLieuService.INXNguyenLieuService")]
    public interface INXNguyenLieuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/DoWork", ReplyAction="http://tempuri.org/INXNguyenLieuService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/DoWork", ReplyAction="http://tempuri.org/INXNguyenLieuService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/layMaPhieuNhap", ReplyAction="http://tempuri.org/INXNguyenLieuService/layMaPhieuNhapResponse")]
        int layMaPhieuNhap();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/layMaPhieuNhap", ReplyAction="http://tempuri.org/INXNguyenLieuService/layMaPhieuNhapResponse")]
        System.Threading.Tasks.Task<int> layMaPhieuNhapAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/layMaPhieuXuat", ReplyAction="http://tempuri.org/INXNguyenLieuService/layMaPhieuXuatResponse")]
        int layMaPhieuXuat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/layMaPhieuXuat", ReplyAction="http://tempuri.org/INXNguyenLieuService/layMaPhieuXuatResponse")]
        System.Threading.Tasks.Task<int> layMaPhieuXuatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/NhapNL", ReplyAction="http://tempuri.org/INXNguyenLieuService/NhapNLResponse")]
        bool NhapNL(DTO_QLCP.NXNguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/NhapNL", ReplyAction="http://tempuri.org/INXNguyenLieuService/NhapNLResponse")]
        System.Threading.Tasks.Task<bool> NhapNLAsync(DTO_QLCP.NXNguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/XoaNhapNL", ReplyAction="http://tempuri.org/INXNguyenLieuService/XoaNhapNLResponse")]
        bool XoaNhapNL(DTO_QLCP.NXNguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/XoaNhapNL", ReplyAction="http://tempuri.org/INXNguyenLieuService/XoaNhapNLResponse")]
        System.Threading.Tasks.Task<bool> XoaNhapNLAsync(DTO_QLCP.NXNguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/XuatNL", ReplyAction="http://tempuri.org/INXNguyenLieuService/XuatNLResponse")]
        bool XuatNL(DTO_QLCP.NXNguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/XuatNL", ReplyAction="http://tempuri.org/INXNguyenLieuService/XuatNLResponse")]
        System.Threading.Tasks.Task<bool> XuatNLAsync(DTO_QLCP.NXNguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/XoaXuatNL", ReplyAction="http://tempuri.org/INXNguyenLieuService/XoaXuatNLResponse")]
        bool XoaXuatNL(DTO_QLCP.NXNguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/XoaXuatNL", ReplyAction="http://tempuri.org/INXNguyenLieuService/XoaXuatNLResponse")]
        System.Threading.Tasks.Task<bool> XoaXuatNLAsync(DTO_QLCP.NXNguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/update_tongtien", ReplyAction="http://tempuri.org/INXNguyenLieuService/update_tongtienResponse")]
        void update_tongtien(int mapn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/update_tongtien", ReplyAction="http://tempuri.org/INXNguyenLieuService/update_tongtienResponse")]
        System.Threading.Tasks.Task update_tongtienAsync(int mapn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/LayDSPN", ReplyAction="http://tempuri.org/INXNguyenLieuService/LayDSPNResponse")]
        System.Data.DataTable LayDSPN();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/LayDSPN", ReplyAction="http://tempuri.org/INXNguyenLieuService/LayDSPNResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> LayDSPNAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/Search_PN", ReplyAction="http://tempuri.org/INXNguyenLieuService/Search_PNResponse")]
        System.Data.DataTable Search_PN(int mapn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/Search_PN", ReplyAction="http://tempuri.org/INXNguyenLieuService/Search_PNResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Search_PNAsync(int mapn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/LayDSPX", ReplyAction="http://tempuri.org/INXNguyenLieuService/LayDSPXResponse")]
        System.Data.DataTable LayDSPX();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/LayDSPX", ReplyAction="http://tempuri.org/INXNguyenLieuService/LayDSPXResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> LayDSPXAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/Search_PX", ReplyAction="http://tempuri.org/INXNguyenLieuService/Search_PXResponse")]
        System.Data.DataTable Search_PX(int mapx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INXNguyenLieuService/Search_PX", ReplyAction="http://tempuri.org/INXNguyenLieuService/Search_PXResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Search_PXAsync(int mapx);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INXNguyenLieuServiceChannel : QuanLiCaPhe.NXNguyenLieuService.INXNguyenLieuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NXNguyenLieuServiceClient : System.ServiceModel.ClientBase<QuanLiCaPhe.NXNguyenLieuService.INXNguyenLieuService>, QuanLiCaPhe.NXNguyenLieuService.INXNguyenLieuService {
        
        public NXNguyenLieuServiceClient() {
        }
        
        public NXNguyenLieuServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NXNguyenLieuServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NXNguyenLieuServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NXNguyenLieuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int layMaPhieuNhap() {
            return base.Channel.layMaPhieuNhap();
        }
        
        public System.Threading.Tasks.Task<int> layMaPhieuNhapAsync() {
            return base.Channel.layMaPhieuNhapAsync();
        }
        
        public int layMaPhieuXuat() {
            return base.Channel.layMaPhieuXuat();
        }
        
        public System.Threading.Tasks.Task<int> layMaPhieuXuatAsync() {
            return base.Channel.layMaPhieuXuatAsync();
        }
        
        public bool NhapNL(DTO_QLCP.NXNguyenLieu nl) {
            return base.Channel.NhapNL(nl);
        }
        
        public System.Threading.Tasks.Task<bool> NhapNLAsync(DTO_QLCP.NXNguyenLieu nl) {
            return base.Channel.NhapNLAsync(nl);
        }
        
        public bool XoaNhapNL(DTO_QLCP.NXNguyenLieu nl) {
            return base.Channel.XoaNhapNL(nl);
        }
        
        public System.Threading.Tasks.Task<bool> XoaNhapNLAsync(DTO_QLCP.NXNguyenLieu nl) {
            return base.Channel.XoaNhapNLAsync(nl);
        }
        
        public bool XuatNL(DTO_QLCP.NXNguyenLieu nl) {
            return base.Channel.XuatNL(nl);
        }
        
        public System.Threading.Tasks.Task<bool> XuatNLAsync(DTO_QLCP.NXNguyenLieu nl) {
            return base.Channel.XuatNLAsync(nl);
        }
        
        public bool XoaXuatNL(DTO_QLCP.NXNguyenLieu nl) {
            return base.Channel.XoaXuatNL(nl);
        }
        
        public System.Threading.Tasks.Task<bool> XoaXuatNLAsync(DTO_QLCP.NXNguyenLieu nl) {
            return base.Channel.XoaXuatNLAsync(nl);
        }
        
        public void update_tongtien(int mapn) {
            base.Channel.update_tongtien(mapn);
        }
        
        public System.Threading.Tasks.Task update_tongtienAsync(int mapn) {
            return base.Channel.update_tongtienAsync(mapn);
        }
        
        public System.Data.DataTable LayDSPN() {
            return base.Channel.LayDSPN();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LayDSPNAsync() {
            return base.Channel.LayDSPNAsync();
        }
        
        public System.Data.DataTable Search_PN(int mapn) {
            return base.Channel.Search_PN(mapn);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Search_PNAsync(int mapn) {
            return base.Channel.Search_PNAsync(mapn);
        }
        
        public System.Data.DataTable LayDSPX() {
            return base.Channel.LayDSPX();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LayDSPXAsync() {
            return base.Channel.LayDSPXAsync();
        }
        
        public System.Data.DataTable Search_PX(int mapx) {
            return base.Channel.Search_PX(mapx);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Search_PXAsync(int mapx) {
            return base.Channel.Search_PXAsync(mapx);
        }
    }
}
