//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCaPhe.DoanhThuService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DoanhThuService.IDoanhThuService")]
    public interface IDoanhThuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoanhThuService/DoWork", ReplyAction="http://tempuri.org/IDoanhThuService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoanhThuService/DoWork", ReplyAction="http://tempuri.org/IDoanhThuService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoanhThuService/kiemTraTonTaiDT", ReplyAction="http://tempuri.org/IDoanhThuService/kiemTraTonTaiDTResponse")]
        bool kiemTraTonTaiDT(System.DateTime ngay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoanhThuService/kiemTraTonTaiDT", ReplyAction="http://tempuri.org/IDoanhThuService/kiemTraTonTaiDTResponse")]
        System.Threading.Tasks.Task<bool> kiemTraTonTaiDTAsync(System.DateTime ngay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoanhThuService/layDoanhThu", ReplyAction="http://tempuri.org/IDoanhThuService/layDoanhThuResponse")]
        string layDoanhThu(System.DateTime ngay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoanhThuService/layDoanhThu", ReplyAction="http://tempuri.org/IDoanhThuService/layDoanhThuResponse")]
        System.Threading.Tasks.Task<string> layDoanhThuAsync(System.DateTime ngay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoanhThuService/ThemDoanhThu", ReplyAction="http://tempuri.org/IDoanhThuService/ThemDoanhThuResponse")]
        bool ThemDoanhThu(DTO_QLCP.DoanhThu dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoanhThuService/ThemDoanhThu", ReplyAction="http://tempuri.org/IDoanhThuService/ThemDoanhThuResponse")]
        System.Threading.Tasks.Task<bool> ThemDoanhThuAsync(DTO_QLCP.DoanhThu dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoanhThuService/SuaDoanhThu", ReplyAction="http://tempuri.org/IDoanhThuService/SuaDoanhThuResponse")]
        bool SuaDoanhThu(DTO_QLCP.DoanhThu dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoanhThuService/SuaDoanhThu", ReplyAction="http://tempuri.org/IDoanhThuService/SuaDoanhThuResponse")]
        System.Threading.Tasks.Task<bool> SuaDoanhThuAsync(DTO_QLCP.DoanhThu dt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDoanhThuServiceChannel : QuanLiCaPhe.DoanhThuService.IDoanhThuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoanhThuServiceClient : System.ServiceModel.ClientBase<QuanLiCaPhe.DoanhThuService.IDoanhThuService>, QuanLiCaPhe.DoanhThuService.IDoanhThuService {
        
        public DoanhThuServiceClient() {
        }
        
        public DoanhThuServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoanhThuServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoanhThuServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoanhThuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool kiemTraTonTaiDT(System.DateTime ngay) {
            return base.Channel.kiemTraTonTaiDT(ngay);
        }
        
        public System.Threading.Tasks.Task<bool> kiemTraTonTaiDTAsync(System.DateTime ngay) {
            return base.Channel.kiemTraTonTaiDTAsync(ngay);
        }
        
        public string layDoanhThu(System.DateTime ngay) {
            return base.Channel.layDoanhThu(ngay);
        }
        
        public System.Threading.Tasks.Task<string> layDoanhThuAsync(System.DateTime ngay) {
            return base.Channel.layDoanhThuAsync(ngay);
        }
        
        public bool ThemDoanhThu(DTO_QLCP.DoanhThu dt) {
            return base.Channel.ThemDoanhThu(dt);
        }
        
        public System.Threading.Tasks.Task<bool> ThemDoanhThuAsync(DTO_QLCP.DoanhThu dt) {
            return base.Channel.ThemDoanhThuAsync(dt);
        }
        
        public bool SuaDoanhThu(DTO_QLCP.DoanhThu dt) {
            return base.Channel.SuaDoanhThu(dt);
        }
        
        public System.Threading.Tasks.Task<bool> SuaDoanhThuAsync(DTO_QLCP.DoanhThu dt) {
            return base.Channel.SuaDoanhThuAsync(dt);
        }
    }
}
